services:
    postgres:
        image: postgres:16-alpine
        container_name: my_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: event_horizon
            POSTGRES_HOST_AUTH_METHOD: md5 # Use md5 instead of trust for better security
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    image-to-text:
        build:  ./image-to-text-service
        container_name: image_to_text_service
        restart: always
        environment:
            - MODEL_NAME=Salesforce/blip-image-captioning-base
            - PORT=5001
        ports:
            - "5001:5001"
        volumes:
            - ./image-to-text-service:/app
        depends_on:
            - postgres

volumes:
    postgres_data:
